// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package manageddatabaseopensearch

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearch",
		reflect.TypeOf((*ManagedDatabaseOpensearch)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "accessControl", GoGetter: "AccessControl"},
			_jsii_.MemberProperty{JsiiProperty: "accessControlInput", GoGetter: "AccessControlInput"},
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "components", GoGetter: "Components"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "extendedAccessControl", GoGetter: "ExtendedAccessControl"},
			_jsii_.MemberProperty{JsiiProperty: "extendedAccessControlInput", GoGetter: "ExtendedAccessControlInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "labels", GoGetter: "Labels"},
			_jsii_.MemberProperty{JsiiProperty: "labelsInput", GoGetter: "LabelsInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "maintenanceWindowDow", GoGetter: "MaintenanceWindowDow"},
			_jsii_.MemberProperty{JsiiProperty: "maintenanceWindowDowInput", GoGetter: "MaintenanceWindowDowInput"},
			_jsii_.MemberProperty{JsiiProperty: "maintenanceWindowTime", GoGetter: "MaintenanceWindowTime"},
			_jsii_.MemberProperty{JsiiProperty: "maintenanceWindowTimeInput", GoGetter: "MaintenanceWindowTimeInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "network", GoGetter: "Network"},
			_jsii_.MemberProperty{JsiiProperty: "networkInput", GoGetter: "NetworkInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "nodeStates", GoGetter: "NodeStates"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "plan", GoGetter: "Plan"},
			_jsii_.MemberProperty{JsiiProperty: "planInput", GoGetter: "PlanInput"},
			_jsii_.MemberProperty{JsiiProperty: "powered", GoGetter: "Powered"},
			_jsii_.MemberProperty{JsiiProperty: "poweredInput", GoGetter: "PoweredInput"},
			_jsii_.MemberProperty{JsiiProperty: "primaryDatabase", GoGetter: "PrimaryDatabase"},
			_jsii_.MemberProperty{JsiiProperty: "properties", GoGetter: "Properties"},
			_jsii_.MemberProperty{JsiiProperty: "propertiesInput", GoGetter: "PropertiesInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putNetwork", GoMethod: "PutNetwork"},
			_jsii_.MemberMethod{JsiiMethod: "putProperties", GoMethod: "PutProperties"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccessControl", GoMethod: "ResetAccessControl"},
			_jsii_.MemberMethod{JsiiMethod: "resetExtendedAccessControl", GoMethod: "ResetExtendedAccessControl"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetLabels", GoMethod: "ResetLabels"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaintenanceWindowDow", GoMethod: "ResetMaintenanceWindowDow"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaintenanceWindowTime", GoMethod: "ResetMaintenanceWindowTime"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetwork", GoMethod: "ResetNetwork"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPowered", GoMethod: "ResetPowered"},
			_jsii_.MemberMethod{JsiiMethod: "resetProperties", GoMethod: "ResetProperties"},
			_jsii_.MemberProperty{JsiiProperty: "serviceHost", GoGetter: "ServiceHost"},
			_jsii_.MemberProperty{JsiiProperty: "servicePassword", GoGetter: "ServicePassword"},
			_jsii_.MemberProperty{JsiiProperty: "servicePort", GoGetter: "ServicePort"},
			_jsii_.MemberProperty{JsiiProperty: "serviceUri", GoGetter: "ServiceUri"},
			_jsii_.MemberProperty{JsiiProperty: "serviceUsername", GoGetter: "ServiceUsername"},
			_jsii_.MemberProperty{JsiiProperty: "state", GoGetter: "State"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "title", GoGetter: "Title"},
			_jsii_.MemberProperty{JsiiProperty: "titleInput", GoGetter: "TitleInput"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "type", GoGetter: "Type"},
			_jsii_.MemberProperty{JsiiProperty: "zone", GoGetter: "Zone"},
			_jsii_.MemberProperty{JsiiProperty: "zoneInput", GoGetter: "ZoneInput"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearch{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchComponents",
		reflect.TypeOf((*ManagedDatabaseOpensearchComponents)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchComponentsList",
		reflect.TypeOf((*ManagedDatabaseOpensearchComponentsList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchComponentsList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchComponentsOutputReference",
		reflect.TypeOf((*ManagedDatabaseOpensearchComponentsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberProperty{JsiiProperty: "component", GoGetter: "Component"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "host", GoGetter: "Host"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "port", GoGetter: "Port"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "route", GoGetter: "Route"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "usage", GoGetter: "Usage"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchComponentsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchConfig",
		reflect.TypeOf((*ManagedDatabaseOpensearchConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchNetwork",
		reflect.TypeOf((*ManagedDatabaseOpensearchNetwork)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchNetworkList",
		reflect.TypeOf((*ManagedDatabaseOpensearchNetworkList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchNetworkList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchNetworkOutputReference",
		reflect.TypeOf((*ManagedDatabaseOpensearchNetworkOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "family", GoGetter: "Family"},
			_jsii_.MemberProperty{JsiiProperty: "familyInput", GoGetter: "FamilyInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "type", GoGetter: "Type"},
			_jsii_.MemberProperty{JsiiProperty: "typeInput", GoGetter: "TypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "uuid", GoGetter: "Uuid"},
			_jsii_.MemberProperty{JsiiProperty: "uuidInput", GoGetter: "UuidInput"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchNetworkOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchNodeStates",
		reflect.TypeOf((*ManagedDatabaseOpensearchNodeStates)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchNodeStatesList",
		reflect.TypeOf((*ManagedDatabaseOpensearchNodeStatesList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchNodeStatesList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchNodeStatesOutputReference",
		reflect.TypeOf((*ManagedDatabaseOpensearchNodeStatesOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "role", GoGetter: "Role"},
			_jsii_.MemberProperty{JsiiProperty: "state", GoGetter: "State"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchNodeStatesOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchProperties",
		reflect.TypeOf((*ManagedDatabaseOpensearchProperties)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesAuthFailureListeners",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesAuthFailureListeners)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesAuthFailureListenersInternalAuthenticationBackendLimiting",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesAuthFailureListenersInternalAuthenticationBackendLimiting)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesAuthFailureListenersInternalAuthenticationBackendLimitingOutputReference",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesAuthFailureListenersInternalAuthenticationBackendLimitingOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "allowedTries", GoGetter: "AllowedTries"},
			_jsii_.MemberProperty{JsiiProperty: "allowedTriesInput", GoGetter: "AllowedTriesInput"},
			_jsii_.MemberProperty{JsiiProperty: "authenticationBackend", GoGetter: "AuthenticationBackend"},
			_jsii_.MemberProperty{JsiiProperty: "authenticationBackendInput", GoGetter: "AuthenticationBackendInput"},
			_jsii_.MemberProperty{JsiiProperty: "blockExpirySeconds", GoGetter: "BlockExpirySeconds"},
			_jsii_.MemberProperty{JsiiProperty: "blockExpirySecondsInput", GoGetter: "BlockExpirySecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "maxBlockedClients", GoGetter: "MaxBlockedClients"},
			_jsii_.MemberProperty{JsiiProperty: "maxBlockedClientsInput", GoGetter: "MaxBlockedClientsInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxTrackedClients", GoGetter: "MaxTrackedClients"},
			_jsii_.MemberProperty{JsiiProperty: "maxTrackedClientsInput", GoGetter: "MaxTrackedClientsInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowedTries", GoMethod: "ResetAllowedTries"},
			_jsii_.MemberMethod{JsiiMethod: "resetAuthenticationBackend", GoMethod: "ResetAuthenticationBackend"},
			_jsii_.MemberMethod{JsiiMethod: "resetBlockExpirySeconds", GoMethod: "ResetBlockExpirySeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxBlockedClients", GoMethod: "ResetMaxBlockedClients"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxTrackedClients", GoMethod: "ResetMaxTrackedClients"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeWindowSeconds", GoMethod: "ResetTimeWindowSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetType", GoMethod: "ResetType"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "timeWindowSeconds", GoGetter: "TimeWindowSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "timeWindowSecondsInput", GoGetter: "TimeWindowSecondsInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "type", GoGetter: "Type"},
			_jsii_.MemberProperty{JsiiProperty: "typeInput", GoGetter: "TypeInput"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchPropertiesAuthFailureListenersInternalAuthenticationBackendLimitingOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesAuthFailureListenersIpRateLimiting",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesAuthFailureListenersIpRateLimiting)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesAuthFailureListenersIpRateLimitingOutputReference",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesAuthFailureListenersIpRateLimitingOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "allowedTries", GoGetter: "AllowedTries"},
			_jsii_.MemberProperty{JsiiProperty: "allowedTriesInput", GoGetter: "AllowedTriesInput"},
			_jsii_.MemberProperty{JsiiProperty: "blockExpirySeconds", GoGetter: "BlockExpirySeconds"},
			_jsii_.MemberProperty{JsiiProperty: "blockExpirySecondsInput", GoGetter: "BlockExpirySecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "maxBlockedClients", GoGetter: "MaxBlockedClients"},
			_jsii_.MemberProperty{JsiiProperty: "maxBlockedClientsInput", GoGetter: "MaxBlockedClientsInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxTrackedClients", GoGetter: "MaxTrackedClients"},
			_jsii_.MemberProperty{JsiiProperty: "maxTrackedClientsInput", GoGetter: "MaxTrackedClientsInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowedTries", GoMethod: "ResetAllowedTries"},
			_jsii_.MemberMethod{JsiiMethod: "resetBlockExpirySeconds", GoMethod: "ResetBlockExpirySeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxBlockedClients", GoMethod: "ResetMaxBlockedClients"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxTrackedClients", GoMethod: "ResetMaxTrackedClients"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeWindowSeconds", GoMethod: "ResetTimeWindowSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetType", GoMethod: "ResetType"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "timeWindowSeconds", GoGetter: "TimeWindowSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "timeWindowSecondsInput", GoGetter: "TimeWindowSecondsInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "type", GoGetter: "Type"},
			_jsii_.MemberProperty{JsiiProperty: "typeInput", GoGetter: "TypeInput"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchPropertiesAuthFailureListenersIpRateLimitingOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesAuthFailureListenersOutputReference",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesAuthFailureListenersOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalAuthenticationBackendLimiting", GoGetter: "InternalAuthenticationBackendLimiting"},
			_jsii_.MemberProperty{JsiiProperty: "internalAuthenticationBackendLimitingInput", GoGetter: "InternalAuthenticationBackendLimitingInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ipRateLimiting", GoGetter: "IpRateLimiting"},
			_jsii_.MemberProperty{JsiiProperty: "ipRateLimitingInput", GoGetter: "IpRateLimitingInput"},
			_jsii_.MemberMethod{JsiiMethod: "putInternalAuthenticationBackendLimiting", GoMethod: "PutInternalAuthenticationBackendLimiting"},
			_jsii_.MemberMethod{JsiiMethod: "putIpRateLimiting", GoMethod: "PutIpRateLimiting"},
			_jsii_.MemberMethod{JsiiMethod: "resetInternalAuthenticationBackendLimiting", GoMethod: "ResetInternalAuthenticationBackendLimiting"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpRateLimiting", GoMethod: "ResetIpRateLimiting"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchPropertiesAuthFailureListenersOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesAzureMigration",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesAzureMigration)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesAzureMigrationOutputReference",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesAzureMigrationOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "account", GoGetter: "Account"},
			_jsii_.MemberProperty{JsiiProperty: "accountInput", GoGetter: "AccountInput"},
			_jsii_.MemberProperty{JsiiProperty: "basePath", GoGetter: "BasePath"},
			_jsii_.MemberProperty{JsiiProperty: "basePathInput", GoGetter: "BasePathInput"},
			_jsii_.MemberProperty{JsiiProperty: "chunkSize", GoGetter: "ChunkSize"},
			_jsii_.MemberProperty{JsiiProperty: "chunkSizeInput", GoGetter: "ChunkSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberProperty{JsiiProperty: "compress", GoGetter: "Compress"},
			_jsii_.MemberProperty{JsiiProperty: "compressInput", GoGetter: "CompressInput"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "container", GoGetter: "Container"},
			_jsii_.MemberProperty{JsiiProperty: "containerInput", GoGetter: "ContainerInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "endpointSuffix", GoGetter: "EndpointSuffix"},
			_jsii_.MemberProperty{JsiiProperty: "endpointSuffixInput", GoGetter: "EndpointSuffixInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "key", GoGetter: "Key"},
			_jsii_.MemberProperty{JsiiProperty: "keyInput", GoGetter: "KeyInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccount", GoMethod: "ResetAccount"},
			_jsii_.MemberMethod{JsiiMethod: "resetBasePath", GoMethod: "ResetBasePath"},
			_jsii_.MemberMethod{JsiiMethod: "resetChunkSize", GoMethod: "ResetChunkSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetCompress", GoMethod: "ResetCompress"},
			_jsii_.MemberMethod{JsiiMethod: "resetContainer", GoMethod: "ResetContainer"},
			_jsii_.MemberMethod{JsiiMethod: "resetEndpointSuffix", GoMethod: "ResetEndpointSuffix"},
			_jsii_.MemberMethod{JsiiMethod: "resetKey", GoMethod: "ResetKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetSasToken", GoMethod: "ResetSasToken"},
			_jsii_.MemberMethod{JsiiMethod: "resetSnapshotName", GoMethod: "ResetSnapshotName"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "sasToken", GoGetter: "SasToken"},
			_jsii_.MemberProperty{JsiiProperty: "sasTokenInput", GoGetter: "SasTokenInput"},
			_jsii_.MemberProperty{JsiiProperty: "snapshotName", GoGetter: "SnapshotName"},
			_jsii_.MemberProperty{JsiiProperty: "snapshotNameInput", GoGetter: "SnapshotNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchPropertiesAzureMigrationOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesGcsMigration",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesGcsMigration)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesGcsMigrationOutputReference",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesGcsMigrationOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "basePath", GoGetter: "BasePath"},
			_jsii_.MemberProperty{JsiiProperty: "basePathInput", GoGetter: "BasePathInput"},
			_jsii_.MemberProperty{JsiiProperty: "bucket", GoGetter: "Bucket"},
			_jsii_.MemberProperty{JsiiProperty: "bucketInput", GoGetter: "BucketInput"},
			_jsii_.MemberProperty{JsiiProperty: "chunkSize", GoGetter: "ChunkSize"},
			_jsii_.MemberProperty{JsiiProperty: "chunkSizeInput", GoGetter: "ChunkSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberProperty{JsiiProperty: "compress", GoGetter: "Compress"},
			_jsii_.MemberProperty{JsiiProperty: "compressInput", GoGetter: "CompressInput"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "credentials", GoGetter: "Credentials"},
			_jsii_.MemberProperty{JsiiProperty: "credentialsInput", GoGetter: "CredentialsInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetBasePath", GoMethod: "ResetBasePath"},
			_jsii_.MemberMethod{JsiiMethod: "resetBucket", GoMethod: "ResetBucket"},
			_jsii_.MemberMethod{JsiiMethod: "resetChunkSize", GoMethod: "ResetChunkSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetCompress", GoMethod: "ResetCompress"},
			_jsii_.MemberMethod{JsiiMethod: "resetCredentials", GoMethod: "ResetCredentials"},
			_jsii_.MemberMethod{JsiiMethod: "resetSnapshotName", GoMethod: "ResetSnapshotName"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "snapshotName", GoGetter: "SnapshotName"},
			_jsii_.MemberProperty{JsiiProperty: "snapshotNameInput", GoGetter: "SnapshotNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchPropertiesGcsMigrationOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesIndexRollup",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesIndexRollup)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesIndexRollupOutputReference",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesIndexRollupOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetRollupDashboardsEnabled", GoMethod: "ResetRollupDashboardsEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetRollupEnabled", GoMethod: "ResetRollupEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetRollupSearchBackoffCount", GoMethod: "ResetRollupSearchBackoffCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetRollupSearchBackoffMillis", GoMethod: "ResetRollupSearchBackoffMillis"},
			_jsii_.MemberMethod{JsiiMethod: "resetRollupSearchSearchAllJobs", GoMethod: "ResetRollupSearchSearchAllJobs"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "rollupDashboardsEnabled", GoGetter: "RollupDashboardsEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "rollupDashboardsEnabledInput", GoGetter: "RollupDashboardsEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "rollupEnabled", GoGetter: "RollupEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "rollupEnabledInput", GoGetter: "RollupEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "rollupSearchBackoffCount", GoGetter: "RollupSearchBackoffCount"},
			_jsii_.MemberProperty{JsiiProperty: "rollupSearchBackoffCountInput", GoGetter: "RollupSearchBackoffCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "rollupSearchBackoffMillis", GoGetter: "RollupSearchBackoffMillis"},
			_jsii_.MemberProperty{JsiiProperty: "rollupSearchBackoffMillisInput", GoGetter: "RollupSearchBackoffMillisInput"},
			_jsii_.MemberProperty{JsiiProperty: "rollupSearchSearchAllJobs", GoGetter: "RollupSearchSearchAllJobs"},
			_jsii_.MemberProperty{JsiiProperty: "rollupSearchSearchAllJobsInput", GoGetter: "RollupSearchSearchAllJobsInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchPropertiesIndexRollupOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesIndexTemplate",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesIndexTemplate)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesIndexTemplateOutputReference",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesIndexTemplateOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "mappingNestedObjectsLimit", GoGetter: "MappingNestedObjectsLimit"},
			_jsii_.MemberProperty{JsiiProperty: "mappingNestedObjectsLimitInput", GoGetter: "MappingNestedObjectsLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "numberOfReplicas", GoGetter: "NumberOfReplicas"},
			_jsii_.MemberProperty{JsiiProperty: "numberOfReplicasInput", GoGetter: "NumberOfReplicasInput"},
			_jsii_.MemberProperty{JsiiProperty: "numberOfShards", GoGetter: "NumberOfShards"},
			_jsii_.MemberProperty{JsiiProperty: "numberOfShardsInput", GoGetter: "NumberOfShardsInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetMappingNestedObjectsLimit", GoMethod: "ResetMappingNestedObjectsLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetNumberOfReplicas", GoMethod: "ResetNumberOfReplicas"},
			_jsii_.MemberMethod{JsiiMethod: "resetNumberOfShards", GoMethod: "ResetNumberOfShards"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchPropertiesIndexTemplateOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesOpenid",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesOpenid)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesOpenidOutputReference",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesOpenidOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "clientId", GoGetter: "ClientId"},
			_jsii_.MemberProperty{JsiiProperty: "clientIdInput", GoGetter: "ClientIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientSecret", GoGetter: "ClientSecret"},
			_jsii_.MemberProperty{JsiiProperty: "clientSecretInput", GoGetter: "ClientSecretInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "connectUrl", GoGetter: "ConnectUrl"},
			_jsii_.MemberProperty{JsiiProperty: "connectUrlInput", GoGetter: "ConnectUrlInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "enabled", GoGetter: "Enabled"},
			_jsii_.MemberProperty{JsiiProperty: "enabledInput", GoGetter: "EnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "header", GoGetter: "Header"},
			_jsii_.MemberProperty{JsiiProperty: "headerInput", GoGetter: "HeaderInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "jwtHeader", GoGetter: "JwtHeader"},
			_jsii_.MemberProperty{JsiiProperty: "jwtHeaderInput", GoGetter: "JwtHeaderInput"},
			_jsii_.MemberProperty{JsiiProperty: "jwtUrlParameter", GoGetter: "JwtUrlParameter"},
			_jsii_.MemberProperty{JsiiProperty: "jwtUrlParameterInput", GoGetter: "JwtUrlParameterInput"},
			_jsii_.MemberProperty{JsiiProperty: "refreshRateLimitCount", GoGetter: "RefreshRateLimitCount"},
			_jsii_.MemberProperty{JsiiProperty: "refreshRateLimitCountInput", GoGetter: "RefreshRateLimitCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "refreshRateLimitTimeWindowMs", GoGetter: "RefreshRateLimitTimeWindowMs"},
			_jsii_.MemberProperty{JsiiProperty: "refreshRateLimitTimeWindowMsInput", GoGetter: "RefreshRateLimitTimeWindowMsInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientId", GoMethod: "ResetClientId"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientSecret", GoMethod: "ResetClientSecret"},
			_jsii_.MemberMethod{JsiiMethod: "resetConnectUrl", GoMethod: "ResetConnectUrl"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnabled", GoMethod: "ResetEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetHeader", GoMethod: "ResetHeader"},
			_jsii_.MemberMethod{JsiiMethod: "resetJwtHeader", GoMethod: "ResetJwtHeader"},
			_jsii_.MemberMethod{JsiiMethod: "resetJwtUrlParameter", GoMethod: "ResetJwtUrlParameter"},
			_jsii_.MemberMethod{JsiiMethod: "resetRefreshRateLimitCount", GoMethod: "ResetRefreshRateLimitCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetRefreshRateLimitTimeWindowMs", GoMethod: "ResetRefreshRateLimitTimeWindowMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetRolesKey", GoMethod: "ResetRolesKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetScope", GoMethod: "ResetScope"},
			_jsii_.MemberMethod{JsiiMethod: "resetSubjectKey", GoMethod: "ResetSubjectKey"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "rolesKey", GoGetter: "RolesKey"},
			_jsii_.MemberProperty{JsiiProperty: "rolesKeyInput", GoGetter: "RolesKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "scope", GoGetter: "Scope"},
			_jsii_.MemberProperty{JsiiProperty: "scopeInput", GoGetter: "ScopeInput"},
			_jsii_.MemberProperty{JsiiProperty: "subjectKey", GoGetter: "SubjectKey"},
			_jsii_.MemberProperty{JsiiProperty: "subjectKeyInput", GoGetter: "SubjectKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchPropertiesOpenidOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesOpensearchDashboards",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesOpensearchDashboards)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesOpensearchDashboardsOutputReference",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesOpensearchDashboardsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "enabled", GoGetter: "Enabled"},
			_jsii_.MemberProperty{JsiiProperty: "enabledInput", GoGetter: "EnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "maxOldSpaceSize", GoGetter: "MaxOldSpaceSize"},
			_jsii_.MemberProperty{JsiiProperty: "maxOldSpaceSizeInput", GoGetter: "MaxOldSpaceSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "opensearchRequestTimeout", GoGetter: "OpensearchRequestTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "opensearchRequestTimeoutInput", GoGetter: "OpensearchRequestTimeoutInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnabled", GoMethod: "ResetEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxOldSpaceSize", GoMethod: "ResetMaxOldSpaceSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetOpensearchRequestTimeout", GoMethod: "ResetOpensearchRequestTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchPropertiesOpensearchDashboardsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesOutputReference",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "actionAutoCreateIndexEnabled", GoGetter: "ActionAutoCreateIndexEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "actionAutoCreateIndexEnabledInput", GoGetter: "ActionAutoCreateIndexEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "actionDestructiveRequiresName", GoGetter: "ActionDestructiveRequiresName"},
			_jsii_.MemberProperty{JsiiProperty: "actionDestructiveRequiresNameInput", GoGetter: "ActionDestructiveRequiresNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "authFailureListeners", GoGetter: "AuthFailureListeners"},
			_jsii_.MemberProperty{JsiiProperty: "authFailureListenersInput", GoGetter: "AuthFailureListenersInput"},
			_jsii_.MemberProperty{JsiiProperty: "automaticUtilityNetworkIpFilter", GoGetter: "AutomaticUtilityNetworkIpFilter"},
			_jsii_.MemberProperty{JsiiProperty: "automaticUtilityNetworkIpFilterInput", GoGetter: "AutomaticUtilityNetworkIpFilterInput"},
			_jsii_.MemberProperty{JsiiProperty: "azureMigration", GoGetter: "AzureMigration"},
			_jsii_.MemberProperty{JsiiProperty: "azureMigrationInput", GoGetter: "AzureMigrationInput"},
			_jsii_.MemberProperty{JsiiProperty: "clusterMaxShardsPerNode", GoGetter: "ClusterMaxShardsPerNode"},
			_jsii_.MemberProperty{JsiiProperty: "clusterMaxShardsPerNodeInput", GoGetter: "ClusterMaxShardsPerNodeInput"},
			_jsii_.MemberProperty{JsiiProperty: "clusterRoutingAllocationNodeConcurrentRecoveries", GoGetter: "ClusterRoutingAllocationNodeConcurrentRecoveries"},
			_jsii_.MemberProperty{JsiiProperty: "clusterRoutingAllocationNodeConcurrentRecoveriesInput", GoGetter: "ClusterRoutingAllocationNodeConcurrentRecoveriesInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "customDomain", GoGetter: "CustomDomain"},
			_jsii_.MemberProperty{JsiiProperty: "customDomainInput", GoGetter: "CustomDomainInput"},
			_jsii_.MemberProperty{JsiiProperty: "emailSenderName", GoGetter: "EmailSenderName"},
			_jsii_.MemberProperty{JsiiProperty: "emailSenderNameInput", GoGetter: "EmailSenderNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "emailSenderPassword", GoGetter: "EmailSenderPassword"},
			_jsii_.MemberProperty{JsiiProperty: "emailSenderPasswordInput", GoGetter: "EmailSenderPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "emailSenderUsername", GoGetter: "EmailSenderUsername"},
			_jsii_.MemberProperty{JsiiProperty: "emailSenderUsernameInput", GoGetter: "EmailSenderUsernameInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableSecurityAudit", GoGetter: "EnableSecurityAudit"},
			_jsii_.MemberProperty{JsiiProperty: "enableSecurityAuditInput", GoGetter: "EnableSecurityAuditInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "gcsMigration", GoGetter: "GcsMigration"},
			_jsii_.MemberProperty{JsiiProperty: "gcsMigrationInput", GoGetter: "GcsMigrationInput"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "httpMaxContentLength", GoGetter: "HttpMaxContentLength"},
			_jsii_.MemberProperty{JsiiProperty: "httpMaxContentLengthInput", GoGetter: "HttpMaxContentLengthInput"},
			_jsii_.MemberProperty{JsiiProperty: "httpMaxHeaderSize", GoGetter: "HttpMaxHeaderSize"},
			_jsii_.MemberProperty{JsiiProperty: "httpMaxHeaderSizeInput", GoGetter: "HttpMaxHeaderSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "httpMaxInitialLineLength", GoGetter: "HttpMaxInitialLineLength"},
			_jsii_.MemberProperty{JsiiProperty: "httpMaxInitialLineLengthInput", GoGetter: "HttpMaxInitialLineLengthInput"},
			_jsii_.MemberProperty{JsiiProperty: "indexPatterns", GoGetter: "IndexPatterns"},
			_jsii_.MemberProperty{JsiiProperty: "indexPatternsInput", GoGetter: "IndexPatternsInput"},
			_jsii_.MemberProperty{JsiiProperty: "indexRollup", GoGetter: "IndexRollup"},
			_jsii_.MemberProperty{JsiiProperty: "indexRollupInput", GoGetter: "IndexRollupInput"},
			_jsii_.MemberProperty{JsiiProperty: "indexTemplate", GoGetter: "IndexTemplate"},
			_jsii_.MemberProperty{JsiiProperty: "indexTemplateInput", GoGetter: "IndexTemplateInput"},
			_jsii_.MemberProperty{JsiiProperty: "indicesFielddataCacheSize", GoGetter: "IndicesFielddataCacheSize"},
			_jsii_.MemberProperty{JsiiProperty: "indicesFielddataCacheSizeInput", GoGetter: "IndicesFielddataCacheSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "indicesMemoryIndexBufferSize", GoGetter: "IndicesMemoryIndexBufferSize"},
			_jsii_.MemberProperty{JsiiProperty: "indicesMemoryIndexBufferSizeInput", GoGetter: "IndicesMemoryIndexBufferSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "indicesMemoryMaxIndexBufferSize", GoGetter: "IndicesMemoryMaxIndexBufferSize"},
			_jsii_.MemberProperty{JsiiProperty: "indicesMemoryMaxIndexBufferSizeInput", GoGetter: "IndicesMemoryMaxIndexBufferSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "indicesMemoryMinIndexBufferSize", GoGetter: "IndicesMemoryMinIndexBufferSize"},
			_jsii_.MemberProperty{JsiiProperty: "indicesMemoryMinIndexBufferSizeInput", GoGetter: "IndicesMemoryMinIndexBufferSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "indicesQueriesCacheSize", GoGetter: "IndicesQueriesCacheSize"},
			_jsii_.MemberProperty{JsiiProperty: "indicesQueriesCacheSizeInput", GoGetter: "IndicesQueriesCacheSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "indicesQueryBoolMaxClauseCount", GoGetter: "IndicesQueryBoolMaxClauseCount"},
			_jsii_.MemberProperty{JsiiProperty: "indicesQueryBoolMaxClauseCountInput", GoGetter: "IndicesQueryBoolMaxClauseCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "indicesRecoveryMaxBytesPerSec", GoGetter: "IndicesRecoveryMaxBytesPerSec"},
			_jsii_.MemberProperty{JsiiProperty: "indicesRecoveryMaxBytesPerSecInput", GoGetter: "IndicesRecoveryMaxBytesPerSecInput"},
			_jsii_.MemberProperty{JsiiProperty: "indicesRecoveryMaxConcurrentFileChunks", GoGetter: "IndicesRecoveryMaxConcurrentFileChunks"},
			_jsii_.MemberProperty{JsiiProperty: "indicesRecoveryMaxConcurrentFileChunksInput", GoGetter: "IndicesRecoveryMaxConcurrentFileChunksInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ipFilter", GoGetter: "IpFilter"},
			_jsii_.MemberProperty{JsiiProperty: "ipFilterInput", GoGetter: "IpFilterInput"},
			_jsii_.MemberProperty{JsiiProperty: "ismEnabled", GoGetter: "IsmEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "ismEnabledInput", GoGetter: "IsmEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryEnabled", GoGetter: "IsmHistoryEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryEnabledInput", GoGetter: "IsmHistoryEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryMaxAge", GoGetter: "IsmHistoryMaxAge"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryMaxAgeInput", GoGetter: "IsmHistoryMaxAgeInput"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryMaxDocs", GoGetter: "IsmHistoryMaxDocs"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryMaxDocsInput", GoGetter: "IsmHistoryMaxDocsInput"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryRolloverCheckPeriod", GoGetter: "IsmHistoryRolloverCheckPeriod"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryRolloverCheckPeriodInput", GoGetter: "IsmHistoryRolloverCheckPeriodInput"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryRolloverRetentionPeriod", GoGetter: "IsmHistoryRolloverRetentionPeriod"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryRolloverRetentionPeriodInput", GoGetter: "IsmHistoryRolloverRetentionPeriodInput"},
			_jsii_.MemberProperty{JsiiProperty: "keepIndexRefreshInterval", GoGetter: "KeepIndexRefreshInterval"},
			_jsii_.MemberProperty{JsiiProperty: "keepIndexRefreshIntervalInput", GoGetter: "KeepIndexRefreshIntervalInput"},
			_jsii_.MemberProperty{JsiiProperty: "knnMemoryCircuitBreakerEnabled", GoGetter: "KnnMemoryCircuitBreakerEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "knnMemoryCircuitBreakerEnabledInput", GoGetter: "KnnMemoryCircuitBreakerEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "knnMemoryCircuitBreakerLimit", GoGetter: "KnnMemoryCircuitBreakerLimit"},
			_jsii_.MemberProperty{JsiiProperty: "knnMemoryCircuitBreakerLimitInput", GoGetter: "KnnMemoryCircuitBreakerLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "openid", GoGetter: "Openid"},
			_jsii_.MemberProperty{JsiiProperty: "openidInput", GoGetter: "OpenidInput"},
			_jsii_.MemberProperty{JsiiProperty: "opensearchDashboards", GoGetter: "OpensearchDashboards"},
			_jsii_.MemberProperty{JsiiProperty: "opensearchDashboardsInput", GoGetter: "OpensearchDashboardsInput"},
			_jsii_.MemberProperty{JsiiProperty: "overrideMainResponseVersion", GoGetter: "OverrideMainResponseVersion"},
			_jsii_.MemberProperty{JsiiProperty: "overrideMainResponseVersionInput", GoGetter: "OverrideMainResponseVersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "pluginsAlertingFilterByBackendRoles", GoGetter: "PluginsAlertingFilterByBackendRoles"},
			_jsii_.MemberProperty{JsiiProperty: "pluginsAlertingFilterByBackendRolesInput", GoGetter: "PluginsAlertingFilterByBackendRolesInput"},
			_jsii_.MemberProperty{JsiiProperty: "publicAccess", GoGetter: "PublicAccess"},
			_jsii_.MemberProperty{JsiiProperty: "publicAccessInput", GoGetter: "PublicAccessInput"},
			_jsii_.MemberMethod{JsiiMethod: "putAuthFailureListeners", GoMethod: "PutAuthFailureListeners"},
			_jsii_.MemberMethod{JsiiMethod: "putAzureMigration", GoMethod: "PutAzureMigration"},
			_jsii_.MemberMethod{JsiiMethod: "putGcsMigration", GoMethod: "PutGcsMigration"},
			_jsii_.MemberMethod{JsiiMethod: "putIndexRollup", GoMethod: "PutIndexRollup"},
			_jsii_.MemberMethod{JsiiMethod: "putIndexTemplate", GoMethod: "PutIndexTemplate"},
			_jsii_.MemberMethod{JsiiMethod: "putOpenid", GoMethod: "PutOpenid"},
			_jsii_.MemberMethod{JsiiMethod: "putOpensearchDashboards", GoMethod: "PutOpensearchDashboards"},
			_jsii_.MemberMethod{JsiiMethod: "putS3Migration", GoMethod: "PutS3Migration"},
			_jsii_.MemberMethod{JsiiMethod: "putSaml", GoMethod: "PutSaml"},
			_jsii_.MemberProperty{JsiiProperty: "reindexRemoteWhitelist", GoGetter: "ReindexRemoteWhitelist"},
			_jsii_.MemberProperty{JsiiProperty: "reindexRemoteWhitelistInput", GoGetter: "ReindexRemoteWhitelistInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetActionAutoCreateIndexEnabled", GoMethod: "ResetActionAutoCreateIndexEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetActionDestructiveRequiresName", GoMethod: "ResetActionDestructiveRequiresName"},
			_jsii_.MemberMethod{JsiiMethod: "resetAuthFailureListeners", GoMethod: "ResetAuthFailureListeners"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutomaticUtilityNetworkIpFilter", GoMethod: "ResetAutomaticUtilityNetworkIpFilter"},
			_jsii_.MemberMethod{JsiiMethod: "resetAzureMigration", GoMethod: "ResetAzureMigration"},
			_jsii_.MemberMethod{JsiiMethod: "resetClusterMaxShardsPerNode", GoMethod: "ResetClusterMaxShardsPerNode"},
			_jsii_.MemberMethod{JsiiMethod: "resetClusterRoutingAllocationNodeConcurrentRecoveries", GoMethod: "ResetClusterRoutingAllocationNodeConcurrentRecoveries"},
			_jsii_.MemberMethod{JsiiMethod: "resetCustomDomain", GoMethod: "ResetCustomDomain"},
			_jsii_.MemberMethod{JsiiMethod: "resetEmailSenderName", GoMethod: "ResetEmailSenderName"},
			_jsii_.MemberMethod{JsiiMethod: "resetEmailSenderPassword", GoMethod: "ResetEmailSenderPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetEmailSenderUsername", GoMethod: "ResetEmailSenderUsername"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableSecurityAudit", GoMethod: "ResetEnableSecurityAudit"},
			_jsii_.MemberMethod{JsiiMethod: "resetGcsMigration", GoMethod: "ResetGcsMigration"},
			_jsii_.MemberMethod{JsiiMethod: "resetHttpMaxContentLength", GoMethod: "ResetHttpMaxContentLength"},
			_jsii_.MemberMethod{JsiiMethod: "resetHttpMaxHeaderSize", GoMethod: "ResetHttpMaxHeaderSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetHttpMaxInitialLineLength", GoMethod: "ResetHttpMaxInitialLineLength"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndexPatterns", GoMethod: "ResetIndexPatterns"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndexRollup", GoMethod: "ResetIndexRollup"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndexTemplate", GoMethod: "ResetIndexTemplate"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndicesFielddataCacheSize", GoMethod: "ResetIndicesFielddataCacheSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndicesMemoryIndexBufferSize", GoMethod: "ResetIndicesMemoryIndexBufferSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndicesMemoryMaxIndexBufferSize", GoMethod: "ResetIndicesMemoryMaxIndexBufferSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndicesMemoryMinIndexBufferSize", GoMethod: "ResetIndicesMemoryMinIndexBufferSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndicesQueriesCacheSize", GoMethod: "ResetIndicesQueriesCacheSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndicesQueryBoolMaxClauseCount", GoMethod: "ResetIndicesQueryBoolMaxClauseCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndicesRecoveryMaxBytesPerSec", GoMethod: "ResetIndicesRecoveryMaxBytesPerSec"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndicesRecoveryMaxConcurrentFileChunks", GoMethod: "ResetIndicesRecoveryMaxConcurrentFileChunks"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpFilter", GoMethod: "ResetIpFilter"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsmEnabled", GoMethod: "ResetIsmEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsmHistoryEnabled", GoMethod: "ResetIsmHistoryEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsmHistoryMaxAge", GoMethod: "ResetIsmHistoryMaxAge"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsmHistoryMaxDocs", GoMethod: "ResetIsmHistoryMaxDocs"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsmHistoryRolloverCheckPeriod", GoMethod: "ResetIsmHistoryRolloverCheckPeriod"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsmHistoryRolloverRetentionPeriod", GoMethod: "ResetIsmHistoryRolloverRetentionPeriod"},
			_jsii_.MemberMethod{JsiiMethod: "resetKeepIndexRefreshInterval", GoMethod: "ResetKeepIndexRefreshInterval"},
			_jsii_.MemberMethod{JsiiMethod: "resetKnnMemoryCircuitBreakerEnabled", GoMethod: "ResetKnnMemoryCircuitBreakerEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetKnnMemoryCircuitBreakerLimit", GoMethod: "ResetKnnMemoryCircuitBreakerLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetOpenid", GoMethod: "ResetOpenid"},
			_jsii_.MemberMethod{JsiiMethod: "resetOpensearchDashboards", GoMethod: "ResetOpensearchDashboards"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideMainResponseVersion", GoMethod: "ResetOverrideMainResponseVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetPluginsAlertingFilterByBackendRoles", GoMethod: "ResetPluginsAlertingFilterByBackendRoles"},
			_jsii_.MemberMethod{JsiiMethod: "resetPublicAccess", GoMethod: "ResetPublicAccess"},
			_jsii_.MemberMethod{JsiiMethod: "resetReindexRemoteWhitelist", GoMethod: "ResetReindexRemoteWhitelist"},
			_jsii_.MemberMethod{JsiiMethod: "resetS3Migration", GoMethod: "ResetS3Migration"},
			_jsii_.MemberMethod{JsiiMethod: "resetSaml", GoMethod: "ResetSaml"},
			_jsii_.MemberMethod{JsiiMethod: "resetScriptMaxCompilationsRate", GoMethod: "ResetScriptMaxCompilationsRate"},
			_jsii_.MemberMethod{JsiiMethod: "resetSearchMaxBuckets", GoMethod: "ResetSearchMaxBuckets"},
			_jsii_.MemberMethod{JsiiMethod: "resetServiceLog", GoMethod: "ResetServiceLog"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolAnalyzeQueueSize", GoMethod: "ResetThreadPoolAnalyzeQueueSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolAnalyzeSize", GoMethod: "ResetThreadPoolAnalyzeSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolForceMergeSize", GoMethod: "ResetThreadPoolForceMergeSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolGetQueueSize", GoMethod: "ResetThreadPoolGetQueueSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolGetSize", GoMethod: "ResetThreadPoolGetSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolSearchQueueSize", GoMethod: "ResetThreadPoolSearchQueueSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolSearchSize", GoMethod: "ResetThreadPoolSearchSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolSearchThrottledQueueSize", GoMethod: "ResetThreadPoolSearchThrottledQueueSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolSearchThrottledSize", GoMethod: "ResetThreadPoolSearchThrottledSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolWriteQueueSize", GoMethod: "ResetThreadPoolWriteQueueSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolWriteSize", GoMethod: "ResetThreadPoolWriteSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetVersion", GoMethod: "ResetVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "s3Migration", GoGetter: "S3Migration"},
			_jsii_.MemberProperty{JsiiProperty: "s3MigrationInput", GoGetter: "S3MigrationInput"},
			_jsii_.MemberProperty{JsiiProperty: "saml", GoGetter: "Saml"},
			_jsii_.MemberProperty{JsiiProperty: "samlInput", GoGetter: "SamlInput"},
			_jsii_.MemberProperty{JsiiProperty: "scriptMaxCompilationsRate", GoGetter: "ScriptMaxCompilationsRate"},
			_jsii_.MemberProperty{JsiiProperty: "scriptMaxCompilationsRateInput", GoGetter: "ScriptMaxCompilationsRateInput"},
			_jsii_.MemberProperty{JsiiProperty: "searchMaxBuckets", GoGetter: "SearchMaxBuckets"},
			_jsii_.MemberProperty{JsiiProperty: "searchMaxBucketsInput", GoGetter: "SearchMaxBucketsInput"},
			_jsii_.MemberProperty{JsiiProperty: "serviceLog", GoGetter: "ServiceLog"},
			_jsii_.MemberProperty{JsiiProperty: "serviceLogInput", GoGetter: "ServiceLogInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolAnalyzeQueueSize", GoGetter: "ThreadPoolAnalyzeQueueSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolAnalyzeQueueSizeInput", GoGetter: "ThreadPoolAnalyzeQueueSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolAnalyzeSize", GoGetter: "ThreadPoolAnalyzeSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolAnalyzeSizeInput", GoGetter: "ThreadPoolAnalyzeSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolForceMergeSize", GoGetter: "ThreadPoolForceMergeSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolForceMergeSizeInput", GoGetter: "ThreadPoolForceMergeSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolGetQueueSize", GoGetter: "ThreadPoolGetQueueSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolGetQueueSizeInput", GoGetter: "ThreadPoolGetQueueSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolGetSize", GoGetter: "ThreadPoolGetSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolGetSizeInput", GoGetter: "ThreadPoolGetSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolSearchQueueSize", GoGetter: "ThreadPoolSearchQueueSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolSearchQueueSizeInput", GoGetter: "ThreadPoolSearchQueueSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolSearchSize", GoGetter: "ThreadPoolSearchSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolSearchSizeInput", GoGetter: "ThreadPoolSearchSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolSearchThrottledQueueSize", GoGetter: "ThreadPoolSearchThrottledQueueSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolSearchThrottledQueueSizeInput", GoGetter: "ThreadPoolSearchThrottledQueueSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolSearchThrottledSize", GoGetter: "ThreadPoolSearchThrottledSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolSearchThrottledSizeInput", GoGetter: "ThreadPoolSearchThrottledSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolWriteQueueSize", GoGetter: "ThreadPoolWriteQueueSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolWriteQueueSizeInput", GoGetter: "ThreadPoolWriteQueueSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolWriteSize", GoGetter: "ThreadPoolWriteSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolWriteSizeInput", GoGetter: "ThreadPoolWriteSizeInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "version", GoGetter: "Version"},
			_jsii_.MemberProperty{JsiiProperty: "versionInput", GoGetter: "VersionInput"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchPropertiesOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesS3Migration",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesS3Migration)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesS3MigrationOutputReference",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesS3MigrationOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "accessKey", GoGetter: "AccessKey"},
			_jsii_.MemberProperty{JsiiProperty: "accessKeyInput", GoGetter: "AccessKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "basePath", GoGetter: "BasePath"},
			_jsii_.MemberProperty{JsiiProperty: "basePathInput", GoGetter: "BasePathInput"},
			_jsii_.MemberProperty{JsiiProperty: "bucket", GoGetter: "Bucket"},
			_jsii_.MemberProperty{JsiiProperty: "bucketInput", GoGetter: "BucketInput"},
			_jsii_.MemberProperty{JsiiProperty: "chunkSize", GoGetter: "ChunkSize"},
			_jsii_.MemberProperty{JsiiProperty: "chunkSizeInput", GoGetter: "ChunkSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberProperty{JsiiProperty: "compress", GoGetter: "Compress"},
			_jsii_.MemberProperty{JsiiProperty: "compressInput", GoGetter: "CompressInput"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "endpoint", GoGetter: "Endpoint"},
			_jsii_.MemberProperty{JsiiProperty: "endpointInput", GoGetter: "EndpointInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "region", GoGetter: "Region"},
			_jsii_.MemberProperty{JsiiProperty: "regionInput", GoGetter: "RegionInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccessKey", GoMethod: "ResetAccessKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetBasePath", GoMethod: "ResetBasePath"},
			_jsii_.MemberMethod{JsiiMethod: "resetBucket", GoMethod: "ResetBucket"},
			_jsii_.MemberMethod{JsiiMethod: "resetChunkSize", GoMethod: "ResetChunkSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetCompress", GoMethod: "ResetCompress"},
			_jsii_.MemberMethod{JsiiMethod: "resetEndpoint", GoMethod: "ResetEndpoint"},
			_jsii_.MemberMethod{JsiiMethod: "resetRegion", GoMethod: "ResetRegion"},
			_jsii_.MemberMethod{JsiiMethod: "resetSecretKey", GoMethod: "ResetSecretKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetServerSideEncryption", GoMethod: "ResetServerSideEncryption"},
			_jsii_.MemberMethod{JsiiMethod: "resetSnapshotName", GoMethod: "ResetSnapshotName"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "secretKey", GoGetter: "SecretKey"},
			_jsii_.MemberProperty{JsiiProperty: "secretKeyInput", GoGetter: "SecretKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "serverSideEncryption", GoGetter: "ServerSideEncryption"},
			_jsii_.MemberProperty{JsiiProperty: "serverSideEncryptionInput", GoGetter: "ServerSideEncryptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "snapshotName", GoGetter: "SnapshotName"},
			_jsii_.MemberProperty{JsiiProperty: "snapshotNameInput", GoGetter: "SnapshotNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchPropertiesS3MigrationOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesSaml",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesSaml)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabaseOpensearch.ManagedDatabaseOpensearchPropertiesSamlOutputReference",
		reflect.TypeOf((*ManagedDatabaseOpensearchPropertiesSamlOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "enabled", GoGetter: "Enabled"},
			_jsii_.MemberProperty{JsiiProperty: "enabledInput", GoGetter: "EnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "idpEntityId", GoGetter: "IdpEntityId"},
			_jsii_.MemberProperty{JsiiProperty: "idpEntityIdInput", GoGetter: "IdpEntityIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "idpMetadataUrl", GoGetter: "IdpMetadataUrl"},
			_jsii_.MemberProperty{JsiiProperty: "idpMetadataUrlInput", GoGetter: "IdpMetadataUrlInput"},
			_jsii_.MemberProperty{JsiiProperty: "idpPemtrustedcasContent", GoGetter: "IdpPemtrustedcasContent"},
			_jsii_.MemberProperty{JsiiProperty: "idpPemtrustedcasContentInput", GoGetter: "IdpPemtrustedcasContentInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnabled", GoMethod: "ResetEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetIdpEntityId", GoMethod: "ResetIdpEntityId"},
			_jsii_.MemberMethod{JsiiMethod: "resetIdpMetadataUrl", GoMethod: "ResetIdpMetadataUrl"},
			_jsii_.MemberMethod{JsiiMethod: "resetIdpPemtrustedcasContent", GoMethod: "ResetIdpPemtrustedcasContent"},
			_jsii_.MemberMethod{JsiiMethod: "resetRolesKey", GoMethod: "ResetRolesKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetSpEntityId", GoMethod: "ResetSpEntityId"},
			_jsii_.MemberMethod{JsiiMethod: "resetSubjectKey", GoMethod: "ResetSubjectKey"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "rolesKey", GoGetter: "RolesKey"},
			_jsii_.MemberProperty{JsiiProperty: "rolesKeyInput", GoGetter: "RolesKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "spEntityId", GoGetter: "SpEntityId"},
			_jsii_.MemberProperty{JsiiProperty: "spEntityIdInput", GoGetter: "SpEntityIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "subjectKey", GoGetter: "SubjectKey"},
			_jsii_.MemberProperty{JsiiProperty: "subjectKeyInput", GoGetter: "SubjectKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabaseOpensearchPropertiesSamlOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
