// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package manageddatabasepostgresql

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresql",
		reflect.TypeOf((*ManagedDatabasePostgresql)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "additionalDiskSpaceGib", GoGetter: "AdditionalDiskSpaceGib"},
			_jsii_.MemberProperty{JsiiProperty: "additionalDiskSpaceGibInput", GoGetter: "AdditionalDiskSpaceGibInput"},
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "components", GoGetter: "Components"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "labels", GoGetter: "Labels"},
			_jsii_.MemberProperty{JsiiProperty: "labelsInput", GoGetter: "LabelsInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "maintenanceWindowDow", GoGetter: "MaintenanceWindowDow"},
			_jsii_.MemberProperty{JsiiProperty: "maintenanceWindowDowInput", GoGetter: "MaintenanceWindowDowInput"},
			_jsii_.MemberProperty{JsiiProperty: "maintenanceWindowTime", GoGetter: "MaintenanceWindowTime"},
			_jsii_.MemberProperty{JsiiProperty: "maintenanceWindowTimeInput", GoGetter: "MaintenanceWindowTimeInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "network", GoGetter: "Network"},
			_jsii_.MemberProperty{JsiiProperty: "networkInput", GoGetter: "NetworkInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "nodeStates", GoGetter: "NodeStates"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "plan", GoGetter: "Plan"},
			_jsii_.MemberProperty{JsiiProperty: "planInput", GoGetter: "PlanInput"},
			_jsii_.MemberProperty{JsiiProperty: "powered", GoGetter: "Powered"},
			_jsii_.MemberProperty{JsiiProperty: "poweredInput", GoGetter: "PoweredInput"},
			_jsii_.MemberProperty{JsiiProperty: "primaryDatabase", GoGetter: "PrimaryDatabase"},
			_jsii_.MemberProperty{JsiiProperty: "properties", GoGetter: "Properties"},
			_jsii_.MemberProperty{JsiiProperty: "propertiesInput", GoGetter: "PropertiesInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putNetwork", GoMethod: "PutNetwork"},
			_jsii_.MemberMethod{JsiiMethod: "putProperties", GoMethod: "PutProperties"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetAdditionalDiskSpaceGib", GoMethod: "ResetAdditionalDiskSpaceGib"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetLabels", GoMethod: "ResetLabels"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaintenanceWindowDow", GoMethod: "ResetMaintenanceWindowDow"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaintenanceWindowTime", GoMethod: "ResetMaintenanceWindowTime"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetwork", GoMethod: "ResetNetwork"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPowered", GoMethod: "ResetPowered"},
			_jsii_.MemberMethod{JsiiMethod: "resetProperties", GoMethod: "ResetProperties"},
			_jsii_.MemberMethod{JsiiMethod: "resetTerminationProtection", GoMethod: "ResetTerminationProtection"},
			_jsii_.MemberProperty{JsiiProperty: "serviceHost", GoGetter: "ServiceHost"},
			_jsii_.MemberProperty{JsiiProperty: "servicePassword", GoGetter: "ServicePassword"},
			_jsii_.MemberProperty{JsiiProperty: "servicePort", GoGetter: "ServicePort"},
			_jsii_.MemberProperty{JsiiProperty: "serviceUri", GoGetter: "ServiceUri"},
			_jsii_.MemberProperty{JsiiProperty: "serviceUsername", GoGetter: "ServiceUsername"},
			_jsii_.MemberProperty{JsiiProperty: "sslmode", GoGetter: "Sslmode"},
			_jsii_.MemberProperty{JsiiProperty: "state", GoGetter: "State"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terminationProtection", GoGetter: "TerminationProtection"},
			_jsii_.MemberProperty{JsiiProperty: "terminationProtectionInput", GoGetter: "TerminationProtectionInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "title", GoGetter: "Title"},
			_jsii_.MemberProperty{JsiiProperty: "titleInput", GoGetter: "TitleInput"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "type", GoGetter: "Type"},
			_jsii_.MemberProperty{JsiiProperty: "zone", GoGetter: "Zone"},
			_jsii_.MemberProperty{JsiiProperty: "zoneInput", GoGetter: "ZoneInput"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabasePostgresql{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlComponents",
		reflect.TypeOf((*ManagedDatabasePostgresqlComponents)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlComponentsList",
		reflect.TypeOf((*ManagedDatabasePostgresqlComponentsList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabasePostgresqlComponentsList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlComponentsOutputReference",
		reflect.TypeOf((*ManagedDatabasePostgresqlComponentsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberProperty{JsiiProperty: "component", GoGetter: "Component"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "host", GoGetter: "Host"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "port", GoGetter: "Port"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "route", GoGetter: "Route"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "usage", GoGetter: "Usage"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabasePostgresqlComponentsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlConfig",
		reflect.TypeOf((*ManagedDatabasePostgresqlConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlNetwork",
		reflect.TypeOf((*ManagedDatabasePostgresqlNetwork)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlNetworkList",
		reflect.TypeOf((*ManagedDatabasePostgresqlNetworkList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabasePostgresqlNetworkList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlNetworkOutputReference",
		reflect.TypeOf((*ManagedDatabasePostgresqlNetworkOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "family", GoGetter: "Family"},
			_jsii_.MemberProperty{JsiiProperty: "familyInput", GoGetter: "FamilyInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "type", GoGetter: "Type"},
			_jsii_.MemberProperty{JsiiProperty: "typeInput", GoGetter: "TypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "uuid", GoGetter: "Uuid"},
			_jsii_.MemberProperty{JsiiProperty: "uuidInput", GoGetter: "UuidInput"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabasePostgresqlNetworkOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlNodeStates",
		reflect.TypeOf((*ManagedDatabasePostgresqlNodeStates)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlNodeStatesList",
		reflect.TypeOf((*ManagedDatabasePostgresqlNodeStatesList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabasePostgresqlNodeStatesList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlNodeStatesOutputReference",
		reflect.TypeOf((*ManagedDatabasePostgresqlNodeStatesOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "role", GoGetter: "Role"},
			_jsii_.MemberProperty{JsiiProperty: "state", GoGetter: "State"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabasePostgresqlNodeStatesOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlProperties",
		reflect.TypeOf((*ManagedDatabasePostgresqlProperties)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlPropertiesMigration",
		reflect.TypeOf((*ManagedDatabasePostgresqlPropertiesMigration)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlPropertiesMigrationOutputReference",
		reflect.TypeOf((*ManagedDatabasePostgresqlPropertiesMigrationOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "dbname", GoGetter: "Dbname"},
			_jsii_.MemberProperty{JsiiProperty: "dbnameInput", GoGetter: "DbnameInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "host", GoGetter: "Host"},
			_jsii_.MemberProperty{JsiiProperty: "hostInput", GoGetter: "HostInput"},
			_jsii_.MemberProperty{JsiiProperty: "ignoreDbs", GoGetter: "IgnoreDbs"},
			_jsii_.MemberProperty{JsiiProperty: "ignoreDbsInput", GoGetter: "IgnoreDbsInput"},
			_jsii_.MemberProperty{JsiiProperty: "ignoreRoles", GoGetter: "IgnoreRoles"},
			_jsii_.MemberProperty{JsiiProperty: "ignoreRolesInput", GoGetter: "IgnoreRolesInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "method", GoGetter: "Method"},
			_jsii_.MemberProperty{JsiiProperty: "methodInput", GoGetter: "MethodInput"},
			_jsii_.MemberProperty{JsiiProperty: "password", GoGetter: "Password"},
			_jsii_.MemberProperty{JsiiProperty: "passwordInput", GoGetter: "PasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "port", GoGetter: "Port"},
			_jsii_.MemberProperty{JsiiProperty: "portInput", GoGetter: "PortInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetDbname", GoMethod: "ResetDbname"},
			_jsii_.MemberMethod{JsiiMethod: "resetHost", GoMethod: "ResetHost"},
			_jsii_.MemberMethod{JsiiMethod: "resetIgnoreDbs", GoMethod: "ResetIgnoreDbs"},
			_jsii_.MemberMethod{JsiiMethod: "resetIgnoreRoles", GoMethod: "ResetIgnoreRoles"},
			_jsii_.MemberMethod{JsiiMethod: "resetMethod", GoMethod: "ResetMethod"},
			_jsii_.MemberMethod{JsiiMethod: "resetPassword", GoMethod: "ResetPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetPort", GoMethod: "ResetPort"},
			_jsii_.MemberMethod{JsiiMethod: "resetSsl", GoMethod: "ResetSsl"},
			_jsii_.MemberMethod{JsiiMethod: "resetUsername", GoMethod: "ResetUsername"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "ssl", GoGetter: "Ssl"},
			_jsii_.MemberProperty{JsiiProperty: "sslInput", GoGetter: "SslInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "username", GoGetter: "Username"},
			_jsii_.MemberProperty{JsiiProperty: "usernameInput", GoGetter: "UsernameInput"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabasePostgresqlPropertiesMigrationOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlPropertiesOutputReference",
		reflect.TypeOf((*ManagedDatabasePostgresqlPropertiesOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "adminPassword", GoGetter: "AdminPassword"},
			_jsii_.MemberProperty{JsiiProperty: "adminPasswordInput", GoGetter: "AdminPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "adminUsername", GoGetter: "AdminUsername"},
			_jsii_.MemberProperty{JsiiProperty: "adminUsernameInput", GoGetter: "AdminUsernameInput"},
			_jsii_.MemberProperty{JsiiProperty: "automaticUtilityNetworkIpFilter", GoGetter: "AutomaticUtilityNetworkIpFilter"},
			_jsii_.MemberProperty{JsiiProperty: "automaticUtilityNetworkIpFilterInput", GoGetter: "AutomaticUtilityNetworkIpFilterInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumAnalyzeScaleFactor", GoGetter: "AutovacuumAnalyzeScaleFactor"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumAnalyzeScaleFactorInput", GoGetter: "AutovacuumAnalyzeScaleFactorInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumAnalyzeThreshold", GoGetter: "AutovacuumAnalyzeThreshold"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumAnalyzeThresholdInput", GoGetter: "AutovacuumAnalyzeThresholdInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumFreezeMaxAge", GoGetter: "AutovacuumFreezeMaxAge"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumFreezeMaxAgeInput", GoGetter: "AutovacuumFreezeMaxAgeInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumMaxWorkers", GoGetter: "AutovacuumMaxWorkers"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumMaxWorkersInput", GoGetter: "AutovacuumMaxWorkersInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumNaptime", GoGetter: "AutovacuumNaptime"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumNaptimeInput", GoGetter: "AutovacuumNaptimeInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumVacuumCostDelay", GoGetter: "AutovacuumVacuumCostDelay"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumVacuumCostDelayInput", GoGetter: "AutovacuumVacuumCostDelayInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumVacuumCostLimit", GoGetter: "AutovacuumVacuumCostLimit"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumVacuumCostLimitInput", GoGetter: "AutovacuumVacuumCostLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumVacuumScaleFactor", GoGetter: "AutovacuumVacuumScaleFactor"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumVacuumScaleFactorInput", GoGetter: "AutovacuumVacuumScaleFactorInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumVacuumThreshold", GoGetter: "AutovacuumVacuumThreshold"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumVacuumThresholdInput", GoGetter: "AutovacuumVacuumThresholdInput"},
			_jsii_.MemberProperty{JsiiProperty: "backupHour", GoGetter: "BackupHour"},
			_jsii_.MemberProperty{JsiiProperty: "backupHourInput", GoGetter: "BackupHourInput"},
			_jsii_.MemberProperty{JsiiProperty: "backupMinute", GoGetter: "BackupMinute"},
			_jsii_.MemberProperty{JsiiProperty: "backupMinuteInput", GoGetter: "BackupMinuteInput"},
			_jsii_.MemberProperty{JsiiProperty: "bgwriterDelay", GoGetter: "BgwriterDelay"},
			_jsii_.MemberProperty{JsiiProperty: "bgwriterDelayInput", GoGetter: "BgwriterDelayInput"},
			_jsii_.MemberProperty{JsiiProperty: "bgwriterFlushAfter", GoGetter: "BgwriterFlushAfter"},
			_jsii_.MemberProperty{JsiiProperty: "bgwriterFlushAfterInput", GoGetter: "BgwriterFlushAfterInput"},
			_jsii_.MemberProperty{JsiiProperty: "bgwriterLruMaxpages", GoGetter: "BgwriterLruMaxpages"},
			_jsii_.MemberProperty{JsiiProperty: "bgwriterLruMaxpagesInput", GoGetter: "BgwriterLruMaxpagesInput"},
			_jsii_.MemberProperty{JsiiProperty: "bgwriterLruMultiplier", GoGetter: "BgwriterLruMultiplier"},
			_jsii_.MemberProperty{JsiiProperty: "bgwriterLruMultiplierInput", GoGetter: "BgwriterLruMultiplierInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "deadlockTimeout", GoGetter: "DeadlockTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "deadlockTimeoutInput", GoGetter: "DeadlockTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "defaultToastCompression", GoGetter: "DefaultToastCompression"},
			_jsii_.MemberProperty{JsiiProperty: "defaultToastCompressionInput", GoGetter: "DefaultToastCompressionInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "idleInTransactionSessionTimeout", GoGetter: "IdleInTransactionSessionTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "idleInTransactionSessionTimeoutInput", GoGetter: "IdleInTransactionSessionTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ioCombineLimit", GoGetter: "IoCombineLimit"},
			_jsii_.MemberProperty{JsiiProperty: "ioCombineLimitInput", GoGetter: "IoCombineLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "ioMaxCombineLimit", GoGetter: "IoMaxCombineLimit"},
			_jsii_.MemberProperty{JsiiProperty: "ioMaxCombineLimitInput", GoGetter: "IoMaxCombineLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "ioMaxConcurrency", GoGetter: "IoMaxConcurrency"},
			_jsii_.MemberProperty{JsiiProperty: "ioMaxConcurrencyInput", GoGetter: "IoMaxConcurrencyInput"},
			_jsii_.MemberProperty{JsiiProperty: "ioMethod", GoGetter: "IoMethod"},
			_jsii_.MemberProperty{JsiiProperty: "ioMethodInput", GoGetter: "IoMethodInput"},
			_jsii_.MemberProperty{JsiiProperty: "ioWorkers", GoGetter: "IoWorkers"},
			_jsii_.MemberProperty{JsiiProperty: "ioWorkersInput", GoGetter: "IoWorkersInput"},
			_jsii_.MemberProperty{JsiiProperty: "ipFilter", GoGetter: "IpFilter"},
			_jsii_.MemberProperty{JsiiProperty: "ipFilterInput", GoGetter: "IpFilterInput"},
			_jsii_.MemberProperty{JsiiProperty: "jit", GoGetter: "Jit"},
			_jsii_.MemberProperty{JsiiProperty: "jitInput", GoGetter: "JitInput"},
			_jsii_.MemberProperty{JsiiProperty: "logAutovacuumMinDuration", GoGetter: "LogAutovacuumMinDuration"},
			_jsii_.MemberProperty{JsiiProperty: "logAutovacuumMinDurationInput", GoGetter: "LogAutovacuumMinDurationInput"},
			_jsii_.MemberProperty{JsiiProperty: "logErrorVerbosity", GoGetter: "LogErrorVerbosity"},
			_jsii_.MemberProperty{JsiiProperty: "logErrorVerbosityInput", GoGetter: "LogErrorVerbosityInput"},
			_jsii_.MemberProperty{JsiiProperty: "logLinePrefix", GoGetter: "LogLinePrefix"},
			_jsii_.MemberProperty{JsiiProperty: "logLinePrefixInput", GoGetter: "LogLinePrefixInput"},
			_jsii_.MemberProperty{JsiiProperty: "logMinDurationStatement", GoGetter: "LogMinDurationStatement"},
			_jsii_.MemberProperty{JsiiProperty: "logMinDurationStatementInput", GoGetter: "LogMinDurationStatementInput"},
			_jsii_.MemberProperty{JsiiProperty: "logTempFiles", GoGetter: "LogTempFiles"},
			_jsii_.MemberProperty{JsiiProperty: "logTempFilesInput", GoGetter: "LogTempFilesInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxConnections", GoGetter: "MaxConnections"},
			_jsii_.MemberProperty{JsiiProperty: "maxConnectionsInput", GoGetter: "MaxConnectionsInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxFilesPerProcess", GoGetter: "MaxFilesPerProcess"},
			_jsii_.MemberProperty{JsiiProperty: "maxFilesPerProcessInput", GoGetter: "MaxFilesPerProcessInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxLocksPerTransaction", GoGetter: "MaxLocksPerTransaction"},
			_jsii_.MemberProperty{JsiiProperty: "maxLocksPerTransactionInput", GoGetter: "MaxLocksPerTransactionInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxLogicalReplicationWorkers", GoGetter: "MaxLogicalReplicationWorkers"},
			_jsii_.MemberProperty{JsiiProperty: "maxLogicalReplicationWorkersInput", GoGetter: "MaxLogicalReplicationWorkersInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxParallelWorkers", GoGetter: "MaxParallelWorkers"},
			_jsii_.MemberProperty{JsiiProperty: "maxParallelWorkersInput", GoGetter: "MaxParallelWorkersInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxParallelWorkersPerGather", GoGetter: "MaxParallelWorkersPerGather"},
			_jsii_.MemberProperty{JsiiProperty: "maxParallelWorkersPerGatherInput", GoGetter: "MaxParallelWorkersPerGatherInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxPredLocksPerTransaction", GoGetter: "MaxPredLocksPerTransaction"},
			_jsii_.MemberProperty{JsiiProperty: "maxPredLocksPerTransactionInput", GoGetter: "MaxPredLocksPerTransactionInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxPreparedTransactions", GoGetter: "MaxPreparedTransactions"},
			_jsii_.MemberProperty{JsiiProperty: "maxPreparedTransactionsInput", GoGetter: "MaxPreparedTransactionsInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxReplicationSlots", GoGetter: "MaxReplicationSlots"},
			_jsii_.MemberProperty{JsiiProperty: "maxReplicationSlotsInput", GoGetter: "MaxReplicationSlotsInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxSlotWalKeepSize", GoGetter: "MaxSlotWalKeepSize"},
			_jsii_.MemberProperty{JsiiProperty: "maxSlotWalKeepSizeInput", GoGetter: "MaxSlotWalKeepSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxStackDepth", GoGetter: "MaxStackDepth"},
			_jsii_.MemberProperty{JsiiProperty: "maxStackDepthInput", GoGetter: "MaxStackDepthInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxStandbyArchiveDelay", GoGetter: "MaxStandbyArchiveDelay"},
			_jsii_.MemberProperty{JsiiProperty: "maxStandbyArchiveDelayInput", GoGetter: "MaxStandbyArchiveDelayInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxStandbyStreamingDelay", GoGetter: "MaxStandbyStreamingDelay"},
			_jsii_.MemberProperty{JsiiProperty: "maxStandbyStreamingDelayInput", GoGetter: "MaxStandbyStreamingDelayInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxSyncWorkersPerSubscription", GoGetter: "MaxSyncWorkersPerSubscription"},
			_jsii_.MemberProperty{JsiiProperty: "maxSyncWorkersPerSubscriptionInput", GoGetter: "MaxSyncWorkersPerSubscriptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxWalSenders", GoGetter: "MaxWalSenders"},
			_jsii_.MemberProperty{JsiiProperty: "maxWalSendersInput", GoGetter: "MaxWalSendersInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxWorkerProcesses", GoGetter: "MaxWorkerProcesses"},
			_jsii_.MemberProperty{JsiiProperty: "maxWorkerProcessesInput", GoGetter: "MaxWorkerProcessesInput"},
			_jsii_.MemberProperty{JsiiProperty: "migration", GoGetter: "Migration"},
			_jsii_.MemberProperty{JsiiProperty: "migrationInput", GoGetter: "MigrationInput"},
			_jsii_.MemberProperty{JsiiProperty: "nodeCount", GoGetter: "NodeCount"},
			_jsii_.MemberProperty{JsiiProperty: "nodeCountInput", GoGetter: "NodeCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "passwordEncryption", GoGetter: "PasswordEncryption"},
			_jsii_.MemberProperty{JsiiProperty: "passwordEncryptionInput", GoGetter: "PasswordEncryptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "pgaudit", GoGetter: "Pgaudit"},
			_jsii_.MemberProperty{JsiiProperty: "pgauditInput", GoGetter: "PgauditInput"},
			_jsii_.MemberProperty{JsiiProperty: "pgbouncer", GoGetter: "Pgbouncer"},
			_jsii_.MemberProperty{JsiiProperty: "pgbouncerInput", GoGetter: "PgbouncerInput"},
			_jsii_.MemberProperty{JsiiProperty: "pglookout", GoGetter: "Pglookout"},
			_jsii_.MemberProperty{JsiiProperty: "pglookoutInput", GoGetter: "PglookoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "pgPartmanBgwInterval", GoGetter: "PgPartmanBgwInterval"},
			_jsii_.MemberProperty{JsiiProperty: "pgPartmanBgwIntervalInput", GoGetter: "PgPartmanBgwIntervalInput"},
			_jsii_.MemberProperty{JsiiProperty: "pgPartmanBgwRole", GoGetter: "PgPartmanBgwRole"},
			_jsii_.MemberProperty{JsiiProperty: "pgPartmanBgwRoleInput", GoGetter: "PgPartmanBgwRoleInput"},
			_jsii_.MemberProperty{JsiiProperty: "pgStatMonitorEnable", GoGetter: "PgStatMonitorEnable"},
			_jsii_.MemberProperty{JsiiProperty: "pgStatMonitorEnableInput", GoGetter: "PgStatMonitorEnableInput"},
			_jsii_.MemberProperty{JsiiProperty: "pgStatMonitorPgsmEnableQueryPlan", GoGetter: "PgStatMonitorPgsmEnableQueryPlan"},
			_jsii_.MemberProperty{JsiiProperty: "pgStatMonitorPgsmEnableQueryPlanInput", GoGetter: "PgStatMonitorPgsmEnableQueryPlanInput"},
			_jsii_.MemberProperty{JsiiProperty: "pgStatMonitorPgsmMaxBuckets", GoGetter: "PgStatMonitorPgsmMaxBuckets"},
			_jsii_.MemberProperty{JsiiProperty: "pgStatMonitorPgsmMaxBucketsInput", GoGetter: "PgStatMonitorPgsmMaxBucketsInput"},
			_jsii_.MemberProperty{JsiiProperty: "pgStatStatementsTrack", GoGetter: "PgStatStatementsTrack"},
			_jsii_.MemberProperty{JsiiProperty: "pgStatStatementsTrackInput", GoGetter: "PgStatStatementsTrackInput"},
			_jsii_.MemberProperty{JsiiProperty: "publicAccess", GoGetter: "PublicAccess"},
			_jsii_.MemberProperty{JsiiProperty: "publicAccessInput", GoGetter: "PublicAccessInput"},
			_jsii_.MemberMethod{JsiiMethod: "putMigration", GoMethod: "PutMigration"},
			_jsii_.MemberMethod{JsiiMethod: "putPgaudit", GoMethod: "PutPgaudit"},
			_jsii_.MemberMethod{JsiiMethod: "putPgbouncer", GoMethod: "PutPgbouncer"},
			_jsii_.MemberMethod{JsiiMethod: "putPglookout", GoMethod: "PutPglookout"},
			_jsii_.MemberMethod{JsiiMethod: "putTimescaledb", GoMethod: "PutTimescaledb"},
			_jsii_.MemberMethod{JsiiMethod: "resetAdminPassword", GoMethod: "ResetAdminPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetAdminUsername", GoMethod: "ResetAdminUsername"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutomaticUtilityNetworkIpFilter", GoMethod: "ResetAutomaticUtilityNetworkIpFilter"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumAnalyzeScaleFactor", GoMethod: "ResetAutovacuumAnalyzeScaleFactor"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumAnalyzeThreshold", GoMethod: "ResetAutovacuumAnalyzeThreshold"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumFreezeMaxAge", GoMethod: "ResetAutovacuumFreezeMaxAge"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumMaxWorkers", GoMethod: "ResetAutovacuumMaxWorkers"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumNaptime", GoMethod: "ResetAutovacuumNaptime"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumVacuumCostDelay", GoMethod: "ResetAutovacuumVacuumCostDelay"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumVacuumCostLimit", GoMethod: "ResetAutovacuumVacuumCostLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumVacuumScaleFactor", GoMethod: "ResetAutovacuumVacuumScaleFactor"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumVacuumThreshold", GoMethod: "ResetAutovacuumVacuumThreshold"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackupHour", GoMethod: "ResetBackupHour"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackupMinute", GoMethod: "ResetBackupMinute"},
			_jsii_.MemberMethod{JsiiMethod: "resetBgwriterDelay", GoMethod: "ResetBgwriterDelay"},
			_jsii_.MemberMethod{JsiiMethod: "resetBgwriterFlushAfter", GoMethod: "ResetBgwriterFlushAfter"},
			_jsii_.MemberMethod{JsiiMethod: "resetBgwriterLruMaxpages", GoMethod: "ResetBgwriterLruMaxpages"},
			_jsii_.MemberMethod{JsiiMethod: "resetBgwriterLruMultiplier", GoMethod: "ResetBgwriterLruMultiplier"},
			_jsii_.MemberMethod{JsiiMethod: "resetDeadlockTimeout", GoMethod: "ResetDeadlockTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetDefaultToastCompression", GoMethod: "ResetDefaultToastCompression"},
			_jsii_.MemberMethod{JsiiMethod: "resetIdleInTransactionSessionTimeout", GoMethod: "ResetIdleInTransactionSessionTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetIoCombineLimit", GoMethod: "ResetIoCombineLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetIoMaxCombineLimit", GoMethod: "ResetIoMaxCombineLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetIoMaxConcurrency", GoMethod: "ResetIoMaxConcurrency"},
			_jsii_.MemberMethod{JsiiMethod: "resetIoMethod", GoMethod: "ResetIoMethod"},
			_jsii_.MemberMethod{JsiiMethod: "resetIoWorkers", GoMethod: "ResetIoWorkers"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpFilter", GoMethod: "ResetIpFilter"},
			_jsii_.MemberMethod{JsiiMethod: "resetJit", GoMethod: "ResetJit"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogAutovacuumMinDuration", GoMethod: "ResetLogAutovacuumMinDuration"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogErrorVerbosity", GoMethod: "ResetLogErrorVerbosity"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogLinePrefix", GoMethod: "ResetLogLinePrefix"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogMinDurationStatement", GoMethod: "ResetLogMinDurationStatement"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogTempFiles", GoMethod: "ResetLogTempFiles"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxConnections", GoMethod: "ResetMaxConnections"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxFilesPerProcess", GoMethod: "ResetMaxFilesPerProcess"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxLocksPerTransaction", GoMethod: "ResetMaxLocksPerTransaction"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxLogicalReplicationWorkers", GoMethod: "ResetMaxLogicalReplicationWorkers"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxParallelWorkers", GoMethod: "ResetMaxParallelWorkers"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxParallelWorkersPerGather", GoMethod: "ResetMaxParallelWorkersPerGather"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxPredLocksPerTransaction", GoMethod: "ResetMaxPredLocksPerTransaction"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxPreparedTransactions", GoMethod: "ResetMaxPreparedTransactions"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxReplicationSlots", GoMethod: "ResetMaxReplicationSlots"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxSlotWalKeepSize", GoMethod: "ResetMaxSlotWalKeepSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxStackDepth", GoMethod: "ResetMaxStackDepth"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxStandbyArchiveDelay", GoMethod: "ResetMaxStandbyArchiveDelay"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxStandbyStreamingDelay", GoMethod: "ResetMaxStandbyStreamingDelay"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxSyncWorkersPerSubscription", GoMethod: "ResetMaxSyncWorkersPerSubscription"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxWalSenders", GoMethod: "ResetMaxWalSenders"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxWorkerProcesses", GoMethod: "ResetMaxWorkerProcesses"},
			_jsii_.MemberMethod{JsiiMethod: "resetMigration", GoMethod: "ResetMigration"},
			_jsii_.MemberMethod{JsiiMethod: "resetNodeCount", GoMethod: "ResetNodeCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetPasswordEncryption", GoMethod: "ResetPasswordEncryption"},
			_jsii_.MemberMethod{JsiiMethod: "resetPgaudit", GoMethod: "ResetPgaudit"},
			_jsii_.MemberMethod{JsiiMethod: "resetPgbouncer", GoMethod: "ResetPgbouncer"},
			_jsii_.MemberMethod{JsiiMethod: "resetPglookout", GoMethod: "ResetPglookout"},
			_jsii_.MemberMethod{JsiiMethod: "resetPgPartmanBgwInterval", GoMethod: "ResetPgPartmanBgwInterval"},
			_jsii_.MemberMethod{JsiiMethod: "resetPgPartmanBgwRole", GoMethod: "ResetPgPartmanBgwRole"},
			_jsii_.MemberMethod{JsiiMethod: "resetPgStatMonitorEnable", GoMethod: "ResetPgStatMonitorEnable"},
			_jsii_.MemberMethod{JsiiMethod: "resetPgStatMonitorPgsmEnableQueryPlan", GoMethod: "ResetPgStatMonitorPgsmEnableQueryPlan"},
			_jsii_.MemberMethod{JsiiMethod: "resetPgStatMonitorPgsmMaxBuckets", GoMethod: "ResetPgStatMonitorPgsmMaxBuckets"},
			_jsii_.MemberMethod{JsiiMethod: "resetPgStatStatementsTrack", GoMethod: "ResetPgStatStatementsTrack"},
			_jsii_.MemberMethod{JsiiMethod: "resetPublicAccess", GoMethod: "ResetPublicAccess"},
			_jsii_.MemberMethod{JsiiMethod: "resetServiceLog", GoMethod: "ResetServiceLog"},
			_jsii_.MemberMethod{JsiiMethod: "resetSharedBuffersPercentage", GoMethod: "ResetSharedBuffersPercentage"},
			_jsii_.MemberMethod{JsiiMethod: "resetSynchronousReplication", GoMethod: "ResetSynchronousReplication"},
			_jsii_.MemberMethod{JsiiMethod: "resetTempFileLimit", GoMethod: "ResetTempFileLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimescaledb", GoMethod: "ResetTimescaledb"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimezone", GoMethod: "ResetTimezone"},
			_jsii_.MemberMethod{JsiiMethod: "resetTrackActivityQuerySize", GoMethod: "ResetTrackActivityQuerySize"},
			_jsii_.MemberMethod{JsiiMethod: "resetTrackCommitTimestamp", GoMethod: "ResetTrackCommitTimestamp"},
			_jsii_.MemberMethod{JsiiMethod: "resetTrackFunctions", GoMethod: "ResetTrackFunctions"},
			_jsii_.MemberMethod{JsiiMethod: "resetTrackIoTiming", GoMethod: "ResetTrackIoTiming"},
			_jsii_.MemberMethod{JsiiMethod: "resetVariant", GoMethod: "ResetVariant"},
			_jsii_.MemberMethod{JsiiMethod: "resetVersion", GoMethod: "ResetVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetWalSenderTimeout", GoMethod: "ResetWalSenderTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetWalWriterDelay", GoMethod: "ResetWalWriterDelay"},
			_jsii_.MemberMethod{JsiiMethod: "resetWorkMem", GoMethod: "ResetWorkMem"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "serviceLog", GoGetter: "ServiceLog"},
			_jsii_.MemberProperty{JsiiProperty: "serviceLogInput", GoGetter: "ServiceLogInput"},
			_jsii_.MemberProperty{JsiiProperty: "sharedBuffersPercentage", GoGetter: "SharedBuffersPercentage"},
			_jsii_.MemberProperty{JsiiProperty: "sharedBuffersPercentageInput", GoGetter: "SharedBuffersPercentageInput"},
			_jsii_.MemberProperty{JsiiProperty: "synchronousReplication", GoGetter: "SynchronousReplication"},
			_jsii_.MemberProperty{JsiiProperty: "synchronousReplicationInput", GoGetter: "SynchronousReplicationInput"},
			_jsii_.MemberProperty{JsiiProperty: "tempFileLimit", GoGetter: "TempFileLimit"},
			_jsii_.MemberProperty{JsiiProperty: "tempFileLimitInput", GoGetter: "TempFileLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "timescaledb", GoGetter: "Timescaledb"},
			_jsii_.MemberProperty{JsiiProperty: "timescaledbInput", GoGetter: "TimescaledbInput"},
			_jsii_.MemberProperty{JsiiProperty: "timezone", GoGetter: "Timezone"},
			_jsii_.MemberProperty{JsiiProperty: "timezoneInput", GoGetter: "TimezoneInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "trackActivityQuerySize", GoGetter: "TrackActivityQuerySize"},
			_jsii_.MemberProperty{JsiiProperty: "trackActivityQuerySizeInput", GoGetter: "TrackActivityQuerySizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "trackCommitTimestamp", GoGetter: "TrackCommitTimestamp"},
			_jsii_.MemberProperty{JsiiProperty: "trackCommitTimestampInput", GoGetter: "TrackCommitTimestampInput"},
			_jsii_.MemberProperty{JsiiProperty: "trackFunctions", GoGetter: "TrackFunctions"},
			_jsii_.MemberProperty{JsiiProperty: "trackFunctionsInput", GoGetter: "TrackFunctionsInput"},
			_jsii_.MemberProperty{JsiiProperty: "trackIoTiming", GoGetter: "TrackIoTiming"},
			_jsii_.MemberProperty{JsiiProperty: "trackIoTimingInput", GoGetter: "TrackIoTimingInput"},
			_jsii_.MemberProperty{JsiiProperty: "variant", GoGetter: "Variant"},
			_jsii_.MemberProperty{JsiiProperty: "variantInput", GoGetter: "VariantInput"},
			_jsii_.MemberProperty{JsiiProperty: "version", GoGetter: "Version"},
			_jsii_.MemberProperty{JsiiProperty: "versionInput", GoGetter: "VersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "walSenderTimeout", GoGetter: "WalSenderTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "walSenderTimeoutInput", GoGetter: "WalSenderTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "walWriterDelay", GoGetter: "WalWriterDelay"},
			_jsii_.MemberProperty{JsiiProperty: "walWriterDelayInput", GoGetter: "WalWriterDelayInput"},
			_jsii_.MemberProperty{JsiiProperty: "workMem", GoGetter: "WorkMem"},
			_jsii_.MemberProperty{JsiiProperty: "workMemInput", GoGetter: "WorkMemInput"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabasePostgresqlPropertiesOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlPropertiesPgaudit",
		reflect.TypeOf((*ManagedDatabasePostgresqlPropertiesPgaudit)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlPropertiesPgauditOutputReference",
		reflect.TypeOf((*ManagedDatabasePostgresqlPropertiesPgauditOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "featureEnabled", GoGetter: "FeatureEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "featureEnabledInput", GoGetter: "FeatureEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "log", GoGetter: "Log"},
			_jsii_.MemberProperty{JsiiProperty: "logCatalog", GoGetter: "LogCatalog"},
			_jsii_.MemberProperty{JsiiProperty: "logCatalogInput", GoGetter: "LogCatalogInput"},
			_jsii_.MemberProperty{JsiiProperty: "logClient", GoGetter: "LogClient"},
			_jsii_.MemberProperty{JsiiProperty: "logClientInput", GoGetter: "LogClientInput"},
			_jsii_.MemberProperty{JsiiProperty: "logInput", GoGetter: "LogInput"},
			_jsii_.MemberProperty{JsiiProperty: "logLevel", GoGetter: "LogLevel"},
			_jsii_.MemberProperty{JsiiProperty: "logLevelInput", GoGetter: "LogLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "logMaxStringLength", GoGetter: "LogMaxStringLength"},
			_jsii_.MemberProperty{JsiiProperty: "logMaxStringLengthInput", GoGetter: "LogMaxStringLengthInput"},
			_jsii_.MemberProperty{JsiiProperty: "logNestedStatements", GoGetter: "LogNestedStatements"},
			_jsii_.MemberProperty{JsiiProperty: "logNestedStatementsInput", GoGetter: "LogNestedStatementsInput"},
			_jsii_.MemberProperty{JsiiProperty: "logParameter", GoGetter: "LogParameter"},
			_jsii_.MemberProperty{JsiiProperty: "logParameterInput", GoGetter: "LogParameterInput"},
			_jsii_.MemberProperty{JsiiProperty: "logParameterMaxSize", GoGetter: "LogParameterMaxSize"},
			_jsii_.MemberProperty{JsiiProperty: "logParameterMaxSizeInput", GoGetter: "LogParameterMaxSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "logRelation", GoGetter: "LogRelation"},
			_jsii_.MemberProperty{JsiiProperty: "logRelationInput", GoGetter: "LogRelationInput"},
			_jsii_.MemberProperty{JsiiProperty: "logRows", GoGetter: "LogRows"},
			_jsii_.MemberProperty{JsiiProperty: "logRowsInput", GoGetter: "LogRowsInput"},
			_jsii_.MemberProperty{JsiiProperty: "logStatement", GoGetter: "LogStatement"},
			_jsii_.MemberProperty{JsiiProperty: "logStatementInput", GoGetter: "LogStatementInput"},
			_jsii_.MemberProperty{JsiiProperty: "logStatementOnce", GoGetter: "LogStatementOnce"},
			_jsii_.MemberProperty{JsiiProperty: "logStatementOnceInput", GoGetter: "LogStatementOnceInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetFeatureEnabled", GoMethod: "ResetFeatureEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetLog", GoMethod: "ResetLog"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogCatalog", GoMethod: "ResetLogCatalog"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogClient", GoMethod: "ResetLogClient"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogLevel", GoMethod: "ResetLogLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogMaxStringLength", GoMethod: "ResetLogMaxStringLength"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogNestedStatements", GoMethod: "ResetLogNestedStatements"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogParameter", GoMethod: "ResetLogParameter"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogParameterMaxSize", GoMethod: "ResetLogParameterMaxSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogRelation", GoMethod: "ResetLogRelation"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogRows", GoMethod: "ResetLogRows"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogStatement", GoMethod: "ResetLogStatement"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogStatementOnce", GoMethod: "ResetLogStatementOnce"},
			_jsii_.MemberMethod{JsiiMethod: "resetRole", GoMethod: "ResetRole"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "role", GoGetter: "Role"},
			_jsii_.MemberProperty{JsiiProperty: "roleInput", GoGetter: "RoleInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabasePostgresqlPropertiesPgauditOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlPropertiesPgbouncer",
		reflect.TypeOf((*ManagedDatabasePostgresqlPropertiesPgbouncer)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlPropertiesPgbouncerOutputReference",
		reflect.TypeOf((*ManagedDatabasePostgresqlPropertiesPgbouncerOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "autodbIdleTimeout", GoGetter: "AutodbIdleTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "autodbIdleTimeoutInput", GoGetter: "AutodbIdleTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "autodbMaxDbConnections", GoGetter: "AutodbMaxDbConnections"},
			_jsii_.MemberProperty{JsiiProperty: "autodbMaxDbConnectionsInput", GoGetter: "AutodbMaxDbConnectionsInput"},
			_jsii_.MemberProperty{JsiiProperty: "autodbPoolMode", GoGetter: "AutodbPoolMode"},
			_jsii_.MemberProperty{JsiiProperty: "autodbPoolModeInput", GoGetter: "AutodbPoolModeInput"},
			_jsii_.MemberProperty{JsiiProperty: "autodbPoolSize", GoGetter: "AutodbPoolSize"},
			_jsii_.MemberProperty{JsiiProperty: "autodbPoolSizeInput", GoGetter: "AutodbPoolSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ignoreStartupParameters", GoGetter: "IgnoreStartupParameters"},
			_jsii_.MemberProperty{JsiiProperty: "ignoreStartupParametersInput", GoGetter: "IgnoreStartupParametersInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "maxPreparedStatements", GoGetter: "MaxPreparedStatements"},
			_jsii_.MemberProperty{JsiiProperty: "maxPreparedStatementsInput", GoGetter: "MaxPreparedStatementsInput"},
			_jsii_.MemberProperty{JsiiProperty: "minPoolSize", GoGetter: "MinPoolSize"},
			_jsii_.MemberProperty{JsiiProperty: "minPoolSizeInput", GoGetter: "MinPoolSizeInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutodbIdleTimeout", GoMethod: "ResetAutodbIdleTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutodbMaxDbConnections", GoMethod: "ResetAutodbMaxDbConnections"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutodbPoolMode", GoMethod: "ResetAutodbPoolMode"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutodbPoolSize", GoMethod: "ResetAutodbPoolSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetIgnoreStartupParameters", GoMethod: "ResetIgnoreStartupParameters"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxPreparedStatements", GoMethod: "ResetMaxPreparedStatements"},
			_jsii_.MemberMethod{JsiiMethod: "resetMinPoolSize", GoMethod: "ResetMinPoolSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetServerIdleTimeout", GoMethod: "ResetServerIdleTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetServerLifetime", GoMethod: "ResetServerLifetime"},
			_jsii_.MemberMethod{JsiiMethod: "resetServerResetQueryAlways", GoMethod: "ResetServerResetQueryAlways"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "serverIdleTimeout", GoGetter: "ServerIdleTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "serverIdleTimeoutInput", GoGetter: "ServerIdleTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "serverLifetime", GoGetter: "ServerLifetime"},
			_jsii_.MemberProperty{JsiiProperty: "serverLifetimeInput", GoGetter: "ServerLifetimeInput"},
			_jsii_.MemberProperty{JsiiProperty: "serverResetQueryAlways", GoGetter: "ServerResetQueryAlways"},
			_jsii_.MemberProperty{JsiiProperty: "serverResetQueryAlwaysInput", GoGetter: "ServerResetQueryAlwaysInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabasePostgresqlPropertiesPgbouncerOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlPropertiesPglookout",
		reflect.TypeOf((*ManagedDatabasePostgresqlPropertiesPglookout)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlPropertiesPglookoutOutputReference",
		reflect.TypeOf((*ManagedDatabasePostgresqlPropertiesPglookoutOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "maxFailoverReplicationTimeLag", GoGetter: "MaxFailoverReplicationTimeLag"},
			_jsii_.MemberProperty{JsiiProperty: "maxFailoverReplicationTimeLagInput", GoGetter: "MaxFailoverReplicationTimeLagInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxFailoverReplicationTimeLag", GoMethod: "ResetMaxFailoverReplicationTimeLag"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabasePostgresqlPropertiesPglookoutOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlPropertiesTimescaledb",
		reflect.TypeOf((*ManagedDatabasePostgresqlPropertiesTimescaledb)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-upcloud.managedDatabasePostgresql.ManagedDatabasePostgresqlPropertiesTimescaledbOutputReference",
		reflect.TypeOf((*ManagedDatabasePostgresqlPropertiesTimescaledbOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "maxBackgroundWorkers", GoGetter: "MaxBackgroundWorkers"},
			_jsii_.MemberProperty{JsiiProperty: "maxBackgroundWorkersInput", GoGetter: "MaxBackgroundWorkersInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxBackgroundWorkers", GoMethod: "ResetMaxBackgroundWorkers"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ManagedDatabasePostgresqlPropertiesTimescaledbOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
